name: Flutter Tag Build

on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: '手动触发时的 Tag 名称 (留空则默认使用当前分支名)'
        required: false
        type: string
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.custom_tag || github.ref_name }}
